#pragma once
static const char API_HELP_HTML[] PROGMEM =

"<!doctype html>\n"
"<html>\n"
"<head>\n"
"  <meta charset=\"utf-8\"/>\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n"
"  <title>Weather Station API</title>\n"
"  <link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><circle cx='50' cy='40' r='18' fill='%23FFB000'/><circle cx='50' cy='40' r='12' fill='%23FFC933'/><path d='M50 10v8M50 62v8M78 40h8M14 40h8M71 19l6-6M23 61l6-6M71 61l6 6M23 19l6 6' stroke='%23FFB000' stroke-width='3' stroke-linecap='round'/><ellipse cx='30' cy='64' rx='16' ry='10' fill='%23E0E0E0'/><ellipse cx='50' cy='60' rx='22' ry='14' fill='%23F0F0F0'/><ellipse cx='70' cy='64' rx='16' ry='10' fill='%23E8E8E8'/></svg>\"/>\n"
"  <style>\n"
"    :root{--bg-color:#fff;--text-color:#333;--card-border:#e0e0e0;--card-bg:#fff;--muted-color:#666;--code-bg:#f5f5f5;--code-border:#e8e8e8;--pre-bg:#f9f9f9;--table-stripe:#f8f8f8;--link-color:#0066cc;--button-bg:#fff;--button-border:#ddd}\n"
"    body.dark-mode{--bg-color:#1a1a1a;--text-color:#e0e0e0;--card-border:#404040;--card-bg:#2a2a2a;--muted-color:#999;--code-bg:#333;--code-border:#444;--pre-bg:#2a2a2a;--table-stripe:#333;--link-color:#66b3ff;--button-bg:#2a2a2a;--button-border:#404040}\n"
"    *{box-sizing:border-box}\n"
"    body{font-family:system-ui,-apple-system,sans-serif;margin:0;padding:20px;line-height:1.6;color:var(--text-color);background-color:var(--bg-color);max-width:1200px;margin:0 auto;transition:background-color .3s,color .3s}\n"
"    h2{margin:0 0 8px 0;font-size:1.8em;font-weight:600}\n"
"    .card{border:1px solid var(--card-border);border-radius:8px;padding:16px;margin:16px 0;background:var(--card-bg);box-shadow:0 1px 3px rgba(0,0,0,.08)}\n"
"    code{background:var(--code-bg);padding:2px 6px;border-radius:4px;font-family:'Consolas','Monaco',monospace;font-size:.9em}\n"
"    .muted{color:var(--muted-color);font-size:.95em}\n"
"    a{color:var(--link-color);text-decoration:none}\n"
"    a:hover{text-decoration:underline}\n"
"    pre{margin:10px 0;overflow-x:auto}\n"
"    pre code{display:block;background:var(--pre-bg);padding:12px;border-radius:6px;border:1px solid var(--code-border);overflow-x:auto;line-height:1.4}\n"
"    table{border-collapse:collapse;font-size:.9em;margin:10px 0}\n"
"    tr:nth-child(even){background:var(--table-stripe)}\n"
"    td{padding:4px 8px;vertical-align:top}\n"
"    td:first-child{padding-right:12px}\n"
"    td:nth-child(2){padding-right:12px;white-space:nowrap}\n"
"    b{font-weight:600;font-family:'Consolas','Monaco',monospace;font-size:.95em}\n"
"    .mt-1{margin-top:8px}\n"
"    .mt-2{margin-top:10px}\n"
"    .header-flex{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:8px}\n"
"    #theme-toggle{padding:8px 12px;font-size:16px;cursor:pointer;border-radius:10px;border:1px solid var(--button-border);background:var(--button-bg);color:var(--text-color);transition:transform .2s}\n"
"    #theme-toggle:hover{transform:scale(1.05)}\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"  <div class=\"header-flex\">\n"
"    <div>\n"
"      <h2>API Reference</h2>\n"
"      <div class=\"muted\">Endpoints served by this device.</div>\n"
"    </div>\n"
"    <button id=\"theme-toggle\" onclick=\"toggleTheme()\" title=\"Toggle dark mode\">☾</button>\n"
"  </div>\n"
"  <div class=\"mt-2\"><a href=\"/\"><- Back to dashboard</a></div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/now</code></div>\n"
"    <div class=\"muted\">Current readings and status flags.</div>\n"
"    <pre><code>{\n"
"  \"epoch\": 1734492345,\n"
"  \"local_time\": \"2025-12-18 22:25\",\n"
#ifdef WIND_SENSOR
"  \"wind_pps\": 0.7,\n"
"  \"wind_ms\": 1.2,\n"
#endif
#ifdef BME280_SENSOR
"  \"bme280_ok\": true,\n"
"  \"temp_c\": 23.4,\n"
"  \"hum_rh\": 55.1,\n"
"  \"press_hpa\": 1012.3,\n"
#endif
#ifdef AIR_QUAL_SENSOR
"  \"pms5003_ok\": true,\n"
"  \"pm1\": 5.2,\n"
"  \"pm25\": 12.8,\n"
"  \"pm10\": 18.4,\n"
"  \"aqi_pm25\": 52,\n"
"  \"aqi_pm25_category\": \"Moderate\",\n"
"  \"aqi_pm10\": 45,\n"
"  \"aqi_pm10_category\": \"Good\",\n"
#endif
"  \"sd_ok\": true,\n"
"  \"cpu_temp_c\": 45.2,\n"
"  \"uptime_s\": 12345,\n"
"  \"retention_days\": 360,\n"
"  \"wifi_rssi\": -65,\n"
"  \"free_heap\": 245000,\n"
"  \"heap_size\": 327680\n"
"}</code></pre>\n"
"    <table>\n"
#ifdef WIND_SENSOR
"      <tr><td><b>wind_ms</b></td><td>m/s</td><td>wind speed in meters per second</td></tr>\n"
#endif
#ifdef BME280_SENSOR
"      <tr><td><b>temp_c</b></td><td>°C</td><td>temperature in Celsius</td></tr>\n"
"      <tr><td><b>hum_rh</b></td><td>%</td><td>relative humidity percentage</td></tr>\n"
"      <tr><td><b>press_hpa</b></td><td>hPa</td><td>atmospheric pressure in hectopascals</td></tr>\n"
#endif
#ifdef AIR_QUAL_SENSOR
"      <tr><td><b>pm1</b></td><td>μg/m³</td><td>particulate matter 1.0 micrograms per cubic meter</td></tr>\n"
"      <tr><td><b>pm25</b></td><td>μg/m³</td><td>particulate matter 2.5 micrograms per cubic meter</td></tr>\n"
"      <tr><td><b>pm10</b></td><td>μg/m³</td><td>particulate matter 10 micrograms per cubic meter</td></tr>\n"
#endif
"      <tr><td><b>cpu_temp_c</b></td><td>°C</td><td>CPU temperature in Celsius</td></tr>\n"
"      <tr><td><b>wifi_rssi</b></td><td>dBm</td><td>WiFi signal strength in decibel-milliwatts</td></tr>\n"
"      <tr><td><b>uptime_s</b></td><td>seconds</td><td>device uptime in seconds</td></tr>\n"
"    </table>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/buckets</code></div>\n"
"    <div class=\"muted\">Last 24h bucketed data with descriptive property names. Chunked transfer.</div>\n"
"    <pre><code>{\n"
"    \"now_epoch\": 1734492345,\n"
"    \"bucket_seconds\": 60,\n"
"    \"buckets\": [\n"
"    {\n"
"      \"timestamp\": 1734489600,\n"
#ifdef WIND_SENSOR
"      \"wind_speed_avg\": 0.8,\n"
"      \"wind_speed_max\": 2.1,\n"
"      \"wind_speed_samples\": 12,\n"
#endif
#ifdef BME280_SENSOR
"      \"temperature\": 22.9,\n"
"      \"humidity\": 56.0,\n"
"      \"pressure\": 1012.1,\n"
#endif
#ifdef AIR_QUAL_SENSOR
"      \"pm1\": 5.2,\n"
"      \"pm25\": 12.8,\n"
"      \"pm10\": 18.4\n"
#endif
"    }\n"
"  ]\n"
"}</code>\n"
"</pre>\n"
"    <table>\n"
#ifdef WIND_SENSOR
"      <tr><td><b>wind_speed_avg</b></td><td>m/s</td><td>average wind speed over 1min bucket</td></tr>\n"
"      <tr><td><b>wind_speed_max</b></td><td>m/s</td><td>maximum wind speed in 1min bucket</td></tr>\n"
#endif
#ifdef BME280_SENSOR
"      <tr><td><b>temperature</b></td><td>°C</td><td>temperature in Celsius</td></tr>\n"
"      <tr><td><b>humidity</b></td><td>%</td><td>relative humidity percentage</td></tr>\n"
"      <tr><td><b>pressure</b></td><td>hPa</td><td>atmospheric pressure in hectopascals</td></tr>\n"
#endif
#ifdef AIR_QUAL_SENSOR
"      <tr><td><b>pm1</b></td><td>μg/m³</td><td>particulate matter 1.0 micrograms per cubic meter</td></tr>\n"
"      <tr><td><b>pm25</b></td><td>μg/m³</td><td>particulate matter 2.5 micrograms per cubic meter</td></tr>\n"
"      <tr><td><b>pm10</b></td><td>μg/m³</td><td>particulate matter 10 micrograms per cubic meter</td></tr>\n"
#endif
"    </table>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/buckets_compact</code></div>\n"
"    <div class=\"muted\">Compact array format (no keys). Full precision floats. Chunked with batching.<br>\n"
"    Array: [epoch, avgWind, maxWind, samples, tempC, humRH, pressHpa, pm1, pm25, pm10]</div>\n"
"    <pre><code>{\n"
"  \"now_epoch\": 1734492345,\n"
"  \"bucket_seconds\": 60,\n"
"  \"buckets\": [\n"
"    [1734489600"
#ifdef WIND_SENSOR
      ", 0.8, 2.1"
#endif
#ifdef BME280_SENSOR
      ", 12, 22.9, 56.0, 1012.1"
#endif
#ifdef AIR_QUAL_SENSOR
      ", 5.2, 12.8, 18.4"
#endif
    "]\n"
"  ]\n"
"}</code></pre>\n"
"    <table>\n"
"      <tr><td><b>[0]</b></td><td>epoch</td><td>Unix timestamp</td></tr>\n"
#ifdef WIND_SENSOR
"      <tr><td><b>[1]</b></td><td>m/s</td><td>average wind speed over 1min bucket</td></tr>\n"
"      <tr><td><b>[2]</b></td><td>m/s</td><td>maximum wind speed in 1min bucket</td></tr>\n"
"      <tr><td><b>[3]</b></td><td>samples</td><td>number of wind samples in bucket</td></tr>\n"
#endif
#ifdef BME280_SENSOR
"      <tr><td><b>[4]</b></td><td>°C</td><td>temperature in Celsius</td></tr>\n"
"      <tr><td><b>[5]</b></td><td>%</td><td>relative humidity percentage</td></tr>\n"
"      <tr><td><b>[6]</b></td><td>hPa</td><td>atmospheric pressure in hectopascals</td></tr>\n"
#endif
#ifdef AIR_QUAL_SENSOR
"      <tr><td><b>[7]</b></td><td>μg/m³</td><td>particulate matter 1.0</td></tr>\n"
"      <tr><td><b>[8]</b></td><td>μg/m³</td><td>particulate matter 2.5</td></tr>\n"
"      <tr><td><b>[9]</b></td><td>μg/m³</td><td>particulate matter 10</td></tr>\n"
#endif
"    </table>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/days</code></div>\n"
"    <div class=\"muted\">Daily summaries.</div>\n"
"    <pre><code>{\n"
"  \"days\": [\n"
"    {\n"
"      \"dayStartEpoch\": 1734480000,\n"
"      \"dayStartLocal\": \"2025-12-18 00:00\",\n"
#ifdef WIND_SENSOR
"      \"avgWind\": 1.2,\n"
"      \"maxWind\": 5.8,\n"
#endif
#ifdef BME280_SENSOR
"      \"avgTemp\": 24.1,\n"
"      \"minTemp\": 19.5,\n"
"      \"maxTemp\": 28.0,\n"
"      \"avgHum\": 58.2,\n"
"      \"minHum\": 44.0,\n"
"      \"maxHum\": 71.5,\n"
"      \"avgPress\": 1012.5,\n"
"      \"minPress\": 1008.2,\n"
"      \"maxPress\": 1016.8,\n"
#endif
#ifdef AIR_QUAL_SENSOR
"      \"avgPM1\": 5.3,\n"
"      \"maxPM1\": 8.2,\n"
"      \"avgPM25\": 12.4,\n"
"      \"maxPM25\": 18.9,\n"
"      \"avgPM10\": 18.1,\n"
"      \"maxPM10\": 25.7\n"
#endif
"    }\n"
"  ]\n"
"}</code></pre>\n"
"    <table>\n"
#ifdef WIND_SENSOR
"      <tr><td><b>avgWind</b></td><td>m/s</td><td>average wind speed for the day</td></tr>\n"
"      <tr><td><b>maxWind</b></td><td>m/s</td><td>maximum wind speed for the day</td></tr>\n"
#endif
#ifdef BME280_SENSOR
"      <tr><td><b>avgTemp</b></td><td>°C</td><td>average temperature for the day</td></tr>\n"
"      <tr><td><b>minTemp</b></td><td>°C</td><td>minimum temperature for the day</td></tr>\n"
"      <tr><td><b>maxTemp</b></td><td>°C</td><td>maximum temperature for the day</td></tr>\n"
"      <tr><td><b>avgHum</b></td><td>%</td><td>average relative humidity for the day</td></tr>\n"
"      <tr><td><b>minHum</b></td><td>%</td><td>minimum relative humidity for the day</td></tr>\n"
"      <tr><td><b>maxHum</b></td><td>%</td><td>maximum relative humidity for the day</td></tr>\n"
"      <tr><td><b>avgPress</b></td><td>hPa</td><td>average atmospheric pressure for the day</td></tr>\n"
"      <tr><td><b>minPress</b></td><td>hPa</td><td>minimum atmospheric pressure for the day</td></tr>\n"
"      <tr><td><b>maxPress</b></td><td>hPa</td><td>maximum atmospheric pressure for the day</td></tr>\n"
#endif
#ifdef AIR_QUAL_SENSOR
"      <tr><td><b>avgPM1</b></td><td>μg/m³</td><td>average particulate matter 1.0 for the day</td></tr>\n"
"      <tr><td><b>maxPM1</b></td><td>μg/m³</td><td>maximum particulate matter 1.0 for the day</td></tr>\n"
"      <tr><td><b>avgPM25</b></td><td>μg/m³</td><td>average particulate matter 2.5 for the day</td></tr>\n"
"      <tr><td><b>maxPM25</b></td><td>μg/m³</td><td>maximum particulate matter 2.5 for the day</td></tr>\n"
"      <tr><td><b>avgPM10</b></td><td>μg/m³</td><td>average particulate matter 10 for the day</td></tr>\n"
"      <tr><td><b>maxPM10</b></td><td>μg/m³</td><td>maximum particulate matter 10 for the day</td></tr>\n"
#endif
"    </table>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/files</code></div>\n"
"    <div class=\"muted\">List available CSV files.</div>\n"
"    <pre><code>{\n"
"  \"ok\": true,\n"
"  \"dir\": \"data\",\n"
"  \"files\": [\n"
"    { \"path\": \"20251218.csv\", \"size\": 12345 },\n"
"    { \"path\": \"20251217.csv\", \"size\": 12001 }\n"
"  ]\n"
"}</code></pre>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/ui_files</code></div>\n"
"    <div class=\"muted\">Get web UI file details (size and last modified timestamp).</div>\n"
"    <pre><code>{\n"
"  \"ok\": true,\n"
"  \"files\": [\n"
"    { \"file\": \"index.html\", \"size\": 8192, \"lastModified\": 1734492345 },\n"
"    { \"file\": \"app.js\", \"size\": 45678, \"lastModified\": 1734492350 }\n"
"  ]\n"
"}</code></pre>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/download?filename=YYYYMMDD.csv</code></div>\n"
"    <div class=\"muted\">Download a specific CSV file.</div>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/download_zip?days=N</code></div>\n"
"    <div class=\"muted\">Stream a ZIP of the last N daily CSV files.</div>\n"
"  </div>\n"
"\n"
"  <h2 style=\"margin-top:32px;\">Endpoints requiring a password</h2>\n"
"  <div class=\"muted mt-1\">These endpoints rate limit after 10 attempts/hour; correct password resets the counter. Failed requests will return 401, and 429 when rate-limited.</div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/clear_data</code> (POST, pw)</div>\n"
"    <div class=\"muted\">Delete all CSV files in <code>/data</code>. Requires <code>pw</code>.</div>\n"
"    <pre><code>{\n"
"  \"ok\": true\n"
"}</code></pre>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/delete</code> (POST, pw)</div>\n"
"    <div class=\"muted\">Delete a single CSV file. Requires <code>filename</code> and <code>pw</code>.</div>\n"
"    <pre><code>{\n"
"  \"ok\": true\n"
"}</code></pre>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/api/reboot</code> (POST, pw)</div>\n"
"    <div class=\"muted\">Immediate reboot of the device. Requires <code>pw</code>.</div>\n"
"    <pre><code>{\n"
"  \"ok\": true\n"
"}</code></pre>\n"
"  </div>\n"
"\n"
"  <div class=\"card\">\n"
"    <div><code>/upload</code> (POST, pw)</div>\n"
"    <div class=\"muted\">Upload files to the SD card. Requires multipart form data with <code>file</code>, <code>path</code>, and <code>pw</code> fields.</div>\n"
"    <div class=\"muted mt-1\">Example:</div>\n"
"    <pre><code>curl -F \"file=@index.html\" -F \"path=/web/index.html\" -F \"pw=yourpassword\" http://device-ip/upload</code></pre>\n"
"    <div class=\"muted mt-1\">Response:</div>\n"
"    <pre><code>{\n"
"  \"ok\": true,\n"
"  \"bytes\": 12345\n"
"}</code></pre>\n"
"  </div>\n"
"\n"
"<script>\n"
"function setCookie(n,v,d){const e=new Date();e.setTime(e.getTime()+(d*864e5));document.cookie=n+\"=\"+v+\";expires=\"+e.toUTCString()+\";path=/\"}\n"
"function getCookie(n){const e=n+\"=\",c=document.cookie.split(';');for(let i=0;i<c.length;i++){let t=c[i];while(t.charAt(0)===' ')t=t.substring(1);if(t.indexOf(e)===0)return t.substring(e.length)}return null}\n"
"function toggleTheme(){const b=document.body,t=document.getElementById('theme-toggle');if(b.classList.contains('dark-mode')){b.classList.remove('dark-mode');t.textContent='☾';t.title='Toggle dark mode';setCookie('theme','light',365)}else{b.classList.add('dark-mode');t.textContent='☼';t.title='Toggle light mode';setCookie('theme','dark',365)}}\n"
"(function(){const t=getCookie('theme'),b=document.getElementById('theme-toggle');if(t==='dark'){document.body.classList.add('dark-mode');b.textContent='☼';b.title='Toggle light mode'}else{b.textContent='☾';b.title='Toggle dark mode'}})();\n"
"</script>\n"
"</body>\n"
"</html>\n";
